// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHgELJ36NdHpOyXgHe12CXKfOAtJIKvA',
    appId: '1:931098478141:web:75672958bfade908518c54',
    messagingSenderId: '931098478141',
    projectId: 'spotify17',
    authDomain: 'spotify17.firebaseapp.com',
    storageBucket: 'spotify17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQivaMJfxodVhNQ10eosTJwYsRBp6fxJ4',
    appId: '1:931098478141:android:0b34e369b42f2a6c518c54',
    messagingSenderId: '931098478141',
    projectId: 'spotify17',
    storageBucket: 'spotify17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0s9zxFfVvyeXAZvCtMdVHmDyy_KiGlGI',
    appId: '1:931098478141:ios:47c7fefdddf70492518c54',
    messagingSenderId: '931098478141',
    projectId: 'spotify17',
    storageBucket: 'spotify17.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0s9zxFfVvyeXAZvCtMdVHmDyy_KiGlGI',
    appId: '1:931098478141:ios:47c7fefdddf70492518c54',
    messagingSenderId: '931098478141',
    projectId: 'spotify17',
    storageBucket: 'spotify17.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClHgELJ36NdHpOyXgHe12CXKfOAtJIKvA',
    appId: '1:931098478141:web:5d0395817f3fc274518c54',
    messagingSenderId: '931098478141',
    projectId: 'spotify17',
    authDomain: 'spotify17.firebaseapp.com',
    storageBucket: 'spotify17.appspot.com',
  );

}